<?php

/**
 * index.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @package     templates
 * @copyright   Copyright (c) 2013 <info@techdivision.com> - TechDivision GmbH
 * @license     http://opensource.org/licenses/osl-3.0.php
 *              Open Software License (OSL 3.0)
 * @author      Johann Zelger <j.zelger@techdivision.com>
 */

/** @var $this \TechDivision\PhpTokenUsage\Templates\IndexTemplate */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->getBaseUrl() ?>">
    <title><?php echo $this->getBaseUrl() ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Webapp created with ApplicationServerProject Stub">
    <meta name="author" content="Your Name">
    <link href="components/require.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
        }
        table td {
            padding: 12px;
        }
        /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }
        .container-narrow > hr {
            margin: 30px 0;
        }

        #projects ul li{
            margin-bottom: 10px;
        }

        /* Main marketing message and sign up button */
        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }
        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }
        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        /* Supporting marketing content */
        .marketing {
            margin: 60px 0;
        }
        .marketing p + h4 {
            margin-top: 28px;
        }

        .nowrap {
            white-space:nowrap;
        }
    </style>

</head>

<body>

<div class="container-narrow">

    <div class="masthead">
        <h3 class="muted"><?php echo $this->getWebappName() ?></h3>
        ... an <a href="http://appserver.io/" target="_blank">appserver</a> demo application
    </div>

    <hr>

    <div class="jumbotron">
        <h2>Welcome!</h2>
        <span>Welcome to the appserver based multithreaded PHP token usage analyzer.</span>
        <span>You will be able to analyze the use of certain PHP language structures within some well known projects over time.</span>
        <br />
        <span>Please be aware that every request <strong>gets calculated new every time</strong>. Caching would not help us show off. ;)</span>
    </div>

    <hr>

    <div class="row-fluid marketing">
        <form method="post" name="input-data">
            <div id="projects" class="span3">
                <strong>Projects to analyze:</strong>
                <ul>
                    <?php foreach ($this->getProjects() as $project) : ?>
                    <li>
                        <?php echo $project->name ?>
                        <input class="push-right" type="checkbox" checked="checked" name="<?php echo strtolower($project->name) ?>" />
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <vr>

            <div id="tokens">
                <strong>Tokens to search for:</strong>
                <select id = "tokenList[]">
                    <option value="0">Please choose</option>
                    <?php foreach ($this->getTokens() as $value => $name) : ?>
                        <option value="<?php echo $value ?>"><?php echo $name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <vr>

            <div class="span6 pull-right">
                <input type="submit" />
            </div>
        </form>
    </div>

</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="components/require.js"></script>
</body>
</html>
